### ISSUE TITLE
What does _get_data_dimensions_rc do? 

### ISSUE THREAD

**Issue by bmoneke** [rgeneaux/pymodaq_plugins_test_pylablib#1]
https://github.com/rgeneaux/pymodaq_plugins_test_pylablib/blob/a5d3b0b869f70359f0a03acb2f5382d42bf10bec/src/pymodaq_plugins_pylablib_camera/daq_viewer_plugins/plugins_2D/daq_2Dviewer_GenericPylablibCamera.py#L143

Why do you use this private method?
What does it return? The detector size? (in this case the get detector size method would be better)

I ask, because I might write a cam driver compatible with this plug-in.

One comment regarding private methods (starting with an underscore): they might change at any time, so do not count on that method.

**Comment by rgeneaux** [comment]
Thanks for letting me know!! I used it because it gave direct access to the width/height of the current image. Get_detector_size just gives the maximal size of the detector (doesn't depend on current hardware roi).
I now replaced it like so
```
        (hstart, hend, vstart, vend, hbin, vbin) = self.controller.get_roi()
        height = hend-hstart
        width = vend-vstart

```
see this commit ff317278ca4143d787ea911a86e58cdc93b878e5

**Comment by bmoneke** [comment]
Ok. Thanks
