### ISSUE TITLE
Update/Clear ROI are toggleable buttons

### ISSUE THREAD

**Issue by bmoneke** [rgeneaux/pymodaq_plugins_test_pylablib#2]
update/clear ROI are toggleable buttons (on/off) such that you have to press them twice in order to set a new ROI / clear the ROI.

Either they should be a pure button (I think pymodaq does not support it yet) or as a workaround, the buttons should deactivate themselves after having been pressed, or they should do their action regardless of the button state (on checking and on unchecking).

**Comment by rgeneaux** [comment]
I thought this was taken care of in the commit_settings:

The buttons have a value of `False `at initialization. Then for example when pressing clear roi (`param.value()` becomes `True`)
```
 if param.name() == "clear_roi":
            if param.value():  # Switching on ROI
                  # do stuff
                self.update_rois(new_roi)
                param.setValue(False)
```

`param.setValue(False)` untoggles the button after actions have been completed.
is it not working for you?

**Comment by bmoneke** [comment]
Unfortunately, it does not work as expected.
Neither in the dashboard nor in the viewer alone.

**Comment by bmoneke** [comment]
The problem is, that the parameter value is not connected back to the Item (widget).
So yes, you set the value to false, but the button remains checked.

**Comment by bmoneke** [comment]
I found the problem. clear/set_acquisition failed such that the method never arrived at param.setValue(False).
